### PR TITLE
Upstream sync

### PR DESCRIPTION
**Pull request by dincho**
```
git remote add upstream git@github.com:erlang/rebar3.git
git fetch upstream
git checkout -b upstream_sync
git merge upstream/master
git push -u origin upstream_sync
```

### CODE REVIEW

**Review by tolbrino — DISMISSED** [review]

**Review by lucafavatella — CHANGES_REQUESTED** [review]
> git merge upstream/master

It looks like this is trying to bring upstream master commit cc788f1f to origin/master, though it somehow rebased hence making history incompatible with upstream master?

```
$ git branch -av --no-contains cc788f1f | grep upstream_sync
  remotes/origin/upstream_sync                  bc809097 Handle incorret app info in escriptize

$ git branch -av --contains cc788f1f | grep upstream/master
  remotes/upstream/master            2f7bde8c Merge pull request #2052 from tsloughter/cirrus-ci
```

Also could you please point to ticket describing desired final state and process.

**Comment by dincho** [comment]
@lucafavatella Should be fine now:

```
$ git branch -av --contains 2f7bde8cd6f7b8a7b21f6fda7a096ef31b4c1cf0
* upstream_sync                d6163b54 Merge remote-tracking branch 'upstream/master' into upstream_sync
  remotes/origin/upstream_sync d6163b54 Merge remote-tracking branch 'upstream/master' into upstream_sync
  remotes/upstream/master      2f7bde8c Merge pull request #2052 from tsloughter/cirrus-ci
```

However CI is now failing for unknown to me reasons

**Comment by dincho** [comment]
> Also could you please point to ticket describing desired final state and process.

There is no ticket with details, just this one: https://www.pivotaltracker.com/story/show/165085675

**Comment by dincho** [comment]
It's not worth the effort for me.

**Pull request closed without merging**
